### ISSUE TITLE
Spam Registration Bots Getting Through on Some Sites now. :-(

### ISSUE THREAD

**Issue by merpdotcom** [collective/collective.emailconfirmationregistration#3]
Bad news, it appears "they" have figured out how to bypass on at least one of my sites now. :-( There are now over 140 fake registrations on the tolkienmoot website that had been working fine to stop them. This is version 1.1.0.b2. Please advise on what I should do to get you information on how they are once again bypassing? I will check the other sites to see if any others are showing registration spam, or if it is only one site.

Some additional sites indeed have been bypassed, brencode, hawketalkshow, omzine, rpgresearch (over 500+!), tolkienscholars, but not merpdotcom, spokanerpg, or half a dozen other sites. The rest (~20 I still hadn't enabled self-registration pending the results of this testing). I am disabling self-registration once again for the "compromised" sites until we can figure out what to try next. Thanks in advance for any suggestions you may have.

**Comment by merpdotcom** [comment]
This is a much lower rate than previously, but still, over 500 bogus accounts on one site in 2 months is not good (previously would have been 2-5x as many).

**Comment by vangheem** [comment]
hhmmm, those are some advanced bots, doing email confirmation and everything. 

Not sure what else there is to do. We have recaptcha, email confirmation and the hidden honey pot field. @mauritsvanrees Do you have any other ideas? Anything else we should do related to https://github.com/collective/collective.honeypot ? Is there another registration form that I'm not aware of that the bots are using instead?

Maybe we add the ability for an admin to approve pending user registration requests?

Or is it possible something else is going on?

**Comment by merpdotcom** [comment]
It would be nice to at least have the option for an admin to approve registration requests, just like the option already exists to moderate posts.

**Comment by vangheem** [comment]
@merpdotcom want to give https://pypi.python.org/pypi/collective.emailconfirmationregistration/1.2.0b1 a try?

After you run the upgrade step, see https://github.com/collective/collective.emailconfirmationregistration#review-registrations on how to activate reviewing registrations.

I'm not sure what else to do. I suppose even huge sites like twitter/facebook get tons of bogus accounts all the time too. If we can find additional tips on how to prevent bogus submissions, I'll try and help with the implementation.

**Comment by mauritsvanrees** [comment]
I have not tried this package, but the implementation looks good.

You currently require that the honeypot field is empty. You could additionally do custom validation to require that the honeypot field _is_ in the request, but still empty. That could stop spammers who are smart enough to know which fields are required in a standard Plone Site.

A spammer might be smart enough to know that the hiddenStructure class on the honeypot field is an indication that it should be ignored. You could do it with inline css (as collective.honeypot does, but that might fail too) or with a more innocent sounding class plus css.

An option may be to add another field with a timestamp and require that there is at least say five seconds between the GET of the original form and the POST of the answer, because humans are less fast at filling in forms than bots are.

**Comment by merpdotcom** [comment]
@vangheem I am installing and testing 1.2.0b1 now. Will report back any findings.

**Comment by merpdotcom** [comment]
@vangheem I can't complete the final step, "To turn on reviewing registrations before the user is created on the site after the user is verified, go to the Configuration registry in Site setup(http://site-url/portal_registry), search for "plone.review_registrations" and enable this setting." that setting doesn't show up at all. I had run buildout, it showed the latest version 1.2.0.b1, stopped and started the cluster, deactivated, activated the app. Still nothing shows up in the registry. Suggestions? Thanks!

**Comment by mauritsvanrees** [comment]
@merpdotcom Did you run the upgrade step? It should be there in the Add-ons control panel.

@vangheem It seems you forgot to push `upgrades.py`. It is there in the PyPI release, but not on github.

**Comment by vangheem** [comment]
@mauritsvanrees thanks for noticing. It is fixed.

@merpdotcom Another new release: https://pypi.python.org/pypi/collective.emailconfirmationregistration/1.2.0b2 Sorry about that. Upgrade step should be fixed.

**Comment by merpdotcom** [comment]
running update to b2, will report back results.

**Comment by merpdotcom** [comment]
Okay, I added collective.emailconfirmationregistration = https://pypi.python.org/pypi/collective.emailconfirmationregistration/1.2.0b to [sources], and now the upgrade button is available after running buildout., and restarting, then clicking the upgrade button, it now shows up in the registry search filter as "False". Selected checkbox to make it true and saved. I then re-enabled self-registration. I am deleting out all the bogus accounts to have a clean slate. I will then test registration to make sure it works normally, and then post any findings. Thanks again!

**Comment by merpdotcom** [comment]
Okay, went through registration process, it worked as expected.
User clicks "Registration", the provides email and Recaptcha.
User then receives verification email and clicks link. User then enters desired Full Name, Username, and (same) valid email. Then clicks submit (for now I have "User sets own password" disabled, I noticed the sites with the highest spam registrations had that enabled btw). 
It then shows page that registration is awaiting approval from admin.
Then logged in with a different browser as admin to approve registration requests by going to http://tolkienscholars.org/@@review-registration-requests (through "Site Setup" > "Add-on Configuration": "Review Registration Requests".  The user request is there, with the option for "Approve" or "Deny".
User then receives email stating "Your user account has been created" (should that be changed to "approved", something like "Your request to create a user account as been approved by the admin"?
Then I clicked the link for activating. 
Enter same username as before, and set new password, entered twice, then submit.
Next page shows "Password has been successfully set and you may log in with your new password".
Login worked successfully!

I wonder if it would be okay on the very first step (submitting email address), have a brief blurb explaining the steps to the user, with an apology for the complexity, but that it is necessary due to abusive bots?

I will enable this on all the sites I was testing, and see how it goes. I will report if there are still any bogus accounts created.

Thanks again!

**Comment by mauritsvanrees** [comment]
In my mind it is not really more complex than normal Plone with 'user sets own passwords' disabled. That setting already means you get an email with a link for setting a password.  The goal for this was originally only so that we know you have set a correct email so that the web master can contact you if needed, and more importantly that you can later reset your own password if you forgot it. It is just that with this package the goal of sending an email is enlarged to also make sure you are not a bot, and that accounts are only added after confirmation.

The email confirmation is a pretty standard part of most sites where you can self register, I would think, so users will be used to it and not find it complex.

The only real difference for the end user is the optional approval by the site admin. So long as that has a clear message after the user has confirmed her email, this is enough I would say.

Just some thoughts. :-)

**Comment by merpdotcom** [comment]
Slight bug? If the site has "Let users select their own passwords" enabled, the user does NOT receive an email when their account is verified by the admin. If the site does NOT have this checked, then they DO receive an email when the admin approves the account creation.

**Comment by vangheem** [comment]
Ah, that is annoying. Thanks, I'll try updating tonight.

**Comment by merpdotcom** [comment]
Crud, it looks like somehow it is still being bypassed. Accounts are being created without ever going to the admin for approval. :-( 17 accounts since yesterday.

**Comment by merpdotcom** [comment]
Does this mean they have figured out some sort of injection bypass method for creating accounts?

**Comment by merpdotcom** [comment]
Above 17 was on rpgresearch (password generated, user can NOT create own password), 6 on earpg, 3 on hawkenterprising, 3 on merp.com, 0 on middle-earthradio, 4 on othermindsmagazine, 0 on spokanerpg,  0 on tolkienmoot, 0 on tolkienscholars.

While the following had "allow user to set own password": 0 on rpgtrailer, 0 on syntheticzen, 0 on spokaneasl.

The rest of the sites (20), I still have user account creation disabled.

I list some of the sites to show the seeming arbitrariness of these attacks.

**Comment by vangheem** [comment]
So all these sites had it so sign-ups were supposed to go through approval? How many were in the approve queue?

Things that could be happening
- there are existing users doing something nefarious?
- there is another form I'm not aware of for signing up?
- my checks are missing something that is getting bypassed?

@mauritsvanrees it seems you have done a lot of research into this. Any ideas? Have you seen this level of spam?

We may need to ask you to install some special logging so we can see what kind of requests are causing this.

**Comment by mauritsvanrees** [comment]
You could try collective.honeypot in its most basic form. Add collective.honeypot to the eggs of your instance. The only thing it then does is: it logs every POST request. This includes logging the form variables that were submitted. Hopefully this gives a clue as to how they are getting in.

You can also activate collective.honeypot more fully. See:
https://pypi.python.org/pypi/collective.honeypot/1.0#activation-on-plone-4
I don't know how well this plays in combination with emailconfirmationregistration.

**Comment by merpdotcom** [comment]
@vangheem Even the sites that have zero users (other than myself), since the overhaul, have the same problem alas. I am the only admin.

**Comment by merpdotcom** [comment]
@vangheem ZERO were in the approval queue.

**Comment by merpdotcom** [comment]
@vangheem Do you want me to install the honeypot as per @mauritsvanrees recommendation?

**Comment by vangheem** [comment]
Zero in the approval queue? You sure you activated it on all the sites?

Sure, give honeypot a try.

**Comment by merpdotcom** [comment]
@vangheem I verified they were enabled for the sites listed, For those that it was enabled, I tested each separately, verifying that requests showed up in the queue, etc. That all worked as expected (except the bug I mentioned earlier regarding if they set their own password option is checked, then when account is approved, the user doesn't receive the notification email). Somehow "they" are getting past the first step with Recaptcha, following the link, creating the fname/lname/account, and completely bypassing the approval process.
I will go ahead and add the honeypot, and re-enable registration for the worst hit sites and see what happens.

**Comment by vangheem** [comment]
Just curious, do you have any other add-ons installed? What versions of Plone again?

**Comment by vangheem** [comment]
https://pypi.python.org/pypi/collective.emailconfirmationregistration/1.2.0b3 for a version that sends emails for those that do not have to reset passwords.

I also noticed I never actually implemented the honey pot field... It seems that wouldn't matter here in any case. Something else is going on.

**Comment by mauritsvanrees** [comment]
Houston, we have a problem... I have just created an account 'maurits' on the tolkienscholars site, without going through checks. I am going to inform the Plone Security Team...

**Comment by mauritsvanrees** [comment]
Mail sent.

It might not be too security sensitive. But when self registration is enabled, please make sure you do not grant authenticated users/members many permissions.

**Comment by merpdotcom** [comment]
Plone 4.3.6 (4310),  Yes there are some other add-on products. Am I going to need to setup a completely vanilla instance to help with testing at this point? I haven't added b3 or the honeypot yet.

**Comment by merpdotcom** [comment]
The Tolkienscholars website has the following products activated (it varies between sites): AddRemoveWidget 1.5.1, Attachment support 4.3, Captcha contact-info 1.2.1, Email confirmation registration 1.2.0b2, Norobots captcha field (collective.z3cform.norobots) 1.4.2.2, Plone Classic Theme 1.3.3, Plone JQuery Integration 1.7.2, Plone JQuery Tools Integration 1.7.0, Plone Quick Upload 1.6.6,  PlonePopoll 2.8b1, Ploneboard 3.6, Ploneboard Notify 0.5.0, PloneboardSubscription 0.9, Quintagroup Captcha Core 0.4.3, ReCaptcha widget 2.0a2, RedirectionTool 1.3.1, Workflow Policy Support (CMFPlacefulWorkflow) 1.5.10, plone.app.collection 1.0.13.

**Comment by merpdotcom** [comment]
The registration for new users is default permissions setting for plone.

**Comment by mauritsvanrees** [comment]
@merpdotcom I now know a way in standard Plone, but with self registration enabled, to create an account without going through any captcha or review or other checks. I am not going to write that method down here of course. I have informed the Plone Security Team.

**Comment by merpdotcom** [comment]
So my several years of dealing with this problem and asking on IRC and elsewhere if there was a way in Plone that was letting them bypass and inject user accounts wasn't a delusion after all?

**Comment by merpdotcom** [comment]
I guess I will go back to disabling user self-registration again until this is figured out. I did just finish updating to b3 and adding the honeypot product. I will disable account registration on all the sites except maybe 1-2 for testing then.

**Comment by mauritsvanrees** [comment]
I guess so. :-(

**Comment by merpdotcom** [comment]
@vangheem I can't seem to get buildout to upgrade from b2 to b3, I tried both the pypi and github [sources], I tried both pinned to b3 and unpinned, and it still only grabs b2. Suggestions?

**Comment by vangheem** [comment]
@merpdotcom pinning should do it.

Also note, https://pypi.python.org/pypi/Products.PloneHotfix20150910/1.0 that addresses bots being able to bypass the registration form.

**Comment by merpdotcom** [comment]
@vangheem I have applied the hotfix, and also updated to b3 now show the version as b3, however it didn't have an upgrade button. But, it appears to have fixed the issue anyway. I tested both with allow user to set password, and not allowed, and both received the email when the admin approved the account. I will now re-enable user registration on about 5-6 key sites and see how they do over the next few days. Thanks again ever so much for your patience and help. This issue had all but killed all my community sites. Hopefully they can come back to life now. I will report back in a few days if all is going well.

**Comment by merpdotcom** [comment]
Btw, @mauritsvanrees thanks for forwarding the issue to the Plone team to get some action taken. Please feel free to test further using the tolkienscholars.org website for now.

**Comment by merpdotcom** [comment]
Well, a HUGE improvement, however:
1) I am not receiving email notification to approve a new user. Is that built into the product, or not there yet?
2) Somehow, a few registrations are still slipping through. Granted, at a MUCH lower rate, but they are still somehow bypassing the "Approve" option. While most sites so far don't have any bogus accounts, one one site, I found one person in the queue for approval, while 5 other accounts are now in my valid user list that weren't there before, and I never approved.

This is a wonderful improvement, but it is concerning that somehow they are finding a way of still slipping through the cracks a little. Suggestions?

Thank you again for all your great help!

**Comment by merpdotcom** [comment]
Well crud. It looks like they have figured out how to bypass it again. :-(  Now about 13 new bogus accounts in about 2 days. Nothing in the "Review Registration Requests".  Have they figured out another Plone vulnerability?

**Comment by vangheem** [comment]
@merpdotcom perhaps you need someone to directly look at your setup? Would you mind granting a plone developer access to look at your server and logs directly? You can email me directly if you're intersted: vangheem@gmail.com

**Comment by merpdotcom** [comment]
That's scary, but yes. I will contact you via email. Thanks.

**Comment by merpdotcom** [comment]
Email sent.

**Comment by merpdotcom** [comment]
Looks like this was because of "Acquisition" and my running about 30 sites in the same instance. Adding collective.siteisolation 0.3dev0 so far seems to have solved the problem. Going to go ahead and close this issue now. Thanks @vangheem for all your help!
