### ISSUE TITLE
still get error with latest release

### ISSUE THREAD

**Issue by rileydog** [collective/collective.emailconfirmationregistration#6]
Hi,  I'm trying 1.2.0b4 in Plone 5 and, unfortunately, I still get the error from previous versions:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 218, in **call**
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module collective.emailconfirmationregistration.browser, line 216, in action_verify
  Module collective.emailconfirmationregistration.browser, line 161, in send_mail
## AttributeError: email_from_address

Note: I confirmed that my site setup does have a valid 'from' email address

Thanks for any help.

**Comment by vangheem** [comment]
It doesn't look like you have the latest installed. Line 161 is not the send_mail method.

**Comment by rileydog** [comment]
Thanks,  that was it.  It works great.  This will help keep junk registrations off site.  This should be part of standard Plone distribution.
